/**
 * Add your global events here
 */

module.exports = {
  AJAX: 'ajax-load',
  TABHIDDEN: 'tab-hidden',
  TABFOCUSED: 'tab-focused',
  OFFLINE: 'offline',
  ONLINE: 'online',
  LOADED: 'load',
  SWIPELEFT: 'swipeleft panleft',
  SWIPERIGHT: 'swiperight panright',
  ALLERTAPPEARED: 'alert-appeared',
  ALERTREMOVED: 'alert-removed',
  LODEDANDREADY: 'load-ready',
  LAZYIMAGEREADY: 'image-lazy-bg-loaded',
  LAZYIMAGESREADY: 'images-lazy-loaded',
  MAPLOADED: 'map-loaded',
  MAPAPILOADED: 'map-api-loaded',
  MAPMARKERCLICK: 'map-marker-click',
  MAPPOPUPCLOSE: 'map-popup-close',
  SCROLL: 'scroll',
  RESIZE: 'resize',
  CAROUSEL_READY: 'bs.carousel.ready',
  SET_TARGET_UPDATE: 'set-target-update',
  RESTORE_FIELD: 'restore-field',
  FORM_INIT_BASICS: 'form-basics',
  FORM_INIT_STEPPED: 'form-init-stepped',
  FORM_INIT_VALIDATE: 'form-init-validate',
  FORM_INIT_VALIDATE_FIELD: 'form-init-validate-field',
  FORM_INIT_STORAGE: 'form-init-storage',
  FORM_VALIDATION_FAILED: 'form-validation-failed',
  FORM_STEPPED_NEW_STEP: 'form-new-step',
  FORM_STEPPED_FIRST_STEP: 'form-first-step',
  FORM_STEPPED_LAST_STEP: 'form-last-step',
  FORM_FIELDS: 'input,textarea,select',
};
